# Generated by Django 2.0 on 2017-12-11 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFlightSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_version', models.CharField(default='VERSION41', max_length=9)),
                ('destination', models.CharField(max_length=4)),
                ('origin', models.CharField(max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('type_of_trip', models.CharField(choices=[('Roundtrip', 'ROUNDTRIP'), ('One-way', 'ONEWAY')], default='Roundtrip', max_length=2)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
