# Generated by Django 2.0 on 2017-12-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedflightsearch',
            name='destination',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='savedflightsearch',
            name='origin',
            field=models.CharField(max_length=3),
        ),
    ]
