# Generated by Django 2.0 on 2018-01-26 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0002_auto_20171212_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=50)),
                ('estimated_roundtrip', models.FloatField()),
                ('flight_time', models.DateTimeField()),
                ('search_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direct_flight', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=50)),
                ('estimated_roundtrip', models.FloatField()),
                ('flight_time', models.DateTimeField()),
                ('search_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direct_flight', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedFlightRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(max_length=10)),
                ('response_version', models.CharField(default='VERSION41', max_length=9)),
                ('destination', models.CharField(max_length=4)),
                ('origin', models.CharField(max_length=4)),
                ('passengers', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='savedflightsearch',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedFlightSearch',
        ),
        migrations.AddField(
            model_name='returnestimate',
            name='flight_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.SavedFlightRoute'),
        ),
        migrations.AddField(
            model_name='departureestimate',
            name='flight_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.SavedFlightRoute'),
        ),
    ]
