# Generated by Django 2.0.1 on 2018-01-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20180126_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedflightroute',
            old_name='passengers',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='savedflightroute',
            old_name='trip_type',
            new_name='type_of_trip',
        ),
        migrations.RemoveField(
            model_name='savedflightroute',
            name='response_version',
        ),
    ]
